# Generated by Django 4.2.4 on 2023-08-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatRoom_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='ph_number',
            field=models.CharField(max_length=11),
        ),
    ]
