# Generated by Django 4.2.4 on 2023-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playModels', '0002_alter_chatroom_chatroom_id_alter_users_ph_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ph_number',
            field=models.CharField(max_length=15),
        ),
    ]
